spring:
  datasource:
    druid:
      username: root
      password: root
      url: jdbc:mysql://192.168.0.33/test?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=false